package handler

import (
	"net/http"

	"github.com/gin-gonic/gin"

	"minibili/internal/logger"
	"minibili/internal/middleware"
	"minibili/internal/pkg/jwttoken"
)

// RegisterRoutes wires HTTP and WebSocket routes.
func RegisterRoutes(r *gin.Engine, a *API, jwtm *jwttoken.Manager) {
	r.Use(corsMiddleware)
	r.Use(logger.GinMiddleware(a.Log))

	r.GET("/api/v1/health", a.Health)

	pub := r.Group("/api/v1")
	{
		pub.POST("/users", a.Register)
		pub.POST("/auth/login", a.Login)
		pub.POST("/auth/refresh", a.Refresh)
		pub.GET("/videos", middleware.OptionalJWT(jwtm), a.ListPublishedVideos)
		pub.GET("/space/:userId", middleware.OptionalJWT(jwtm), a.GetUserPublic)
		pub.GET("/space/:userId/videos", middleware.OptionalJWT(jwtm), a.ListUserPublishedVideos)
		pub.GET("/space/:userId/favorites", middleware.OptionalJWT(jwtm), a.ListUserFavorites)
		pub.GET("/space/:userId/favorite-folders", middleware.OptionalJWT(jwtm), a.ListUserFavoriteFolders)
		pub.GET("/space/:userId/recent-coins", middleware.OptionalJWT(jwtm), a.ListUserRecentCoinVideos)
		pub.GET("/space/:userId/following", middleware.OptionalJWT(jwtm), a.ListUserFollowing)
		pub.GET("/space/:userId/followers", middleware.OptionalJWT(jwtm), a.ListUserFollowers)
		pub.GET("/videos/:id", middleware.OptionalJWT(jwtm), a.GetVideo)
		pub.GET("/videos/:id/comments", middleware.OptionalJWT(jwtm), a.ListComments)
		pub.GET("/articles/:id", middleware.OptionalJWT(jwtm), a.GetArticle)
		pub.GET("/articles/:id/comments", middleware.OptionalJWT(jwtm), a.ListArticleComments)
		pub.GET("/space/:userId/articles", middleware.OptionalJWT(jwtm), a.ListUserPublishedArticles)
		pub.GET("/space/:userId/dynamics", middleware.OptionalJWT(jwtm), a.ListUserPublishedDynamics)
		pub.GET("/user-dynamics/:id", middleware.OptionalJWT(jwtm), a.GetUserDynamic)
		pub.GET("/user-dynamics/:id/comments", middleware.OptionalJWT(jwtm), a.ListDynamicComments)
		pub.GET("/space/:userId/article-favorites", middleware.OptionalJWT(jwtm), a.ListUserArticleFavorites)
		pub.GET("/stats/home", a.HomeStats)
		pub.GET("/hot-search", a.HotSearchList)
		pub.GET("/home-banners", a.ListHomeBanners)
		pub.GET("/search", a.SearchAll)
		pub.GET("/search/suggest", middleware.OptionalJWT(jwtm), a.SearchSuggest)
		// Module 2: Player chapters/bitrates (public)
		pub.GET("/videos/:id/chapters", a.ListVideoChapters)
		pub.GET("/videos/:id/bitrates", a.ListVideoBitrates)
		// Module 3: Subtitles (public list)
		pub.GET("/videos/:id/subtitles", a.ListSubtitles)
		pub.GET("/videos/:id/subtitles/:subtitleId", a.GetSubtitle)
		// Module 7: Feed & Ranking (public)
		pub.GET("/feed/recommendation", a.GetRecommendationFeed)
		pub.GET("/leaderboard", a.GetLeaderboard)
		pub.GET("/zones/:zone/recommendation", a.GetZoneRecommendation)
		// Module 21: Feature flag check (public)
		pub.GET("/config/feature-flags/:key", a.AdminCheckFeatureFlag)
		// Module 9: Special pages (public)
		pub.GET("/specials", a.ListPublicSpecialPages)
		pub.GET("/specials/:slug", a.GetPublicSpecialPage)

		pub.POST("/admin/auth/login", a.AdminLogin)
		pub.POST("/admin/auth/refresh", a.AdminRefresh)
	}

	admin := r.Group("/api/v1/admin")
	admin.Use(middleware.AdminJWTAuth(jwtm))
	{
		// Read-only (all authenticated admins)
		admin.GET("/me", a.AdminMe)
		admin.GET("/users", a.AdminListUsers)
		admin.GET("/users/:id", a.AdminGetUser)
		admin.GET("/users/:id/violations", a.AdminGetUserViolations)
		admin.GET("/home-banners", a.AdminListBanners)
		admin.GET("/videos", a.AdminListVideos)
		admin.GET("/videos/:id", a.AdminGetVideo)
		admin.GET("/comments", a.AdminListComments)
		admin.GET("/comments/:id", a.AdminGetComment)
		admin.GET("/reports", a.AdminListReports)
		admin.GET("/dashboard", a.AdminDashboard)
		admin.GET("/articles", a.AdminListArticles)
		admin.GET("/articles/:id", a.AdminGetArticle)
		admin.GET("/dynamics", a.AdminListDynamics)
		admin.GET("/dynamics/:id", a.AdminGetDynamic)

		// Permission-protected: user.ban
		userOps := admin.Group("", middleware.RequirePermission(a.DB, "user", "ban"))
		userOps.POST("/users/:id/ban", a.AdminBanUser)
		userOps.POST("/users/:id/unban", a.AdminUnbanUser)
		userOps.POST("/users/:id/delete", a.AdminDeleteUser)

		// Permission-protected: video.delete
		vOps := admin.Group("", middleware.RequirePermission(a.DB, "video", "approve"))
		vOps.POST("/videos/:id/approve", a.AdminApproveVideo)
		vOps.POST("/videos/:id/reject", a.AdminRejectVideo)
		vOps.POST("/videos/:id/delete", a.AdminDeleteVideo)
		vOps.DELETE("/videos/:id", a.AdminDeleteVideo)

		// Permission-protected: comment.delete
		cOps := admin.Group("", middleware.RequirePermission(a.DB, "comment", "delete"))
		cOps.POST("/comments/:id/delete", a.AdminDeleteComment)
		cOps.DELETE("/comments/:id", a.AdminDeleteComment)

		// Permission-protected: ticket.handle (reports)
		rOps := admin.Group("", middleware.RequirePermission(a.DB, "ticket", "handle"))
		rOps.POST("/reports/:id/handle", a.AdminHandleReport)
		rOps.POST("/reports/batch", a.AdminBatchHandleReports)
		rOps.DELETE("/reports/:id", a.AdminDeleteReport)

		// Permission-protected: article.approve
		aOps := admin.Group("", middleware.RequirePermission(a.DB, "article", "approve"))
		aOps.POST("/articles/:id/approve", a.AdminApproveArticle)
		aOps.POST("/articles/:id/reject", a.AdminRejectArticle)
		aOps.POST("/articles/:id/delete", a.AdminDeleteArticle)
		aOps.DELETE("/articles/:id", a.AdminDeleteArticle)

		// Dynamic management (admin only, no special permission)
		admin.POST("/dynamics/:id/delete", a.AdminDeleteDynamic)
		admin.DELETE("/dynamics/:id", a.AdminDeleteDynamic)
		// Unrestricted remaining routes
		admin.POST("/home-banners", a.AdminCreateBanner)
		admin.POST("/home-banners/upload-image", a.AdminUploadBannerImage)
		admin.POST("/home-banners/:id/image", a.AdminUploadBannerImageByID)
		admin.PUT("/home-banners/:id", a.AdminUpdateBanner)
		admin.DELETE("/home-banners/:id", a.AdminDeleteBanner)
		admin.GET("/hot-search/ops", a.AdminListHotSearchOps)
		admin.GET("/hot-search/dashboard", a.AdminHotSearchDashboard)
		admin.GET("/hot-search/preview", a.AdminPreviewHotSearch)
		admin.POST("/hot-search/ops", a.AdminCreateHotSearchOp)
		admin.POST("/hot-search/quick-op", a.AdminQuickHotSearchOp)
		admin.POST("/hot-search/reorder", a.AdminReorderHotSearch)
		admin.POST("/hot-search/display-order/reset", a.AdminResetHotSearchDisplayOrder)
		admin.POST("/hot-search/redis/remove", a.AdminRemoveHotSearchRedis)
		admin.POST("/hot-search/redis/boost", a.AdminBoostHotSearchRedis)
		admin.PUT("/hot-search/ops/:id", a.AdminUpdateHotSearchOp)
		admin.DELETE("/hot-search/ops/:id", a.AdminDeleteHotSearchOp)
		admin.GET("/agent-settings", a.AdminGetAgentSettings)
		admin.PUT("/agent-settings", a.AdminPutAgentSettings)
		admin.POST("/agent-settings/avatar", a.AdminUploadAgentAvatar)
		admin.GET("/agent-profiles", a.AdminListAgentProfiles)
		admin.POST("/agent-profiles", a.AdminCreateAgentProfile)
		admin.PUT("/agent-profiles/:id", a.AdminUpdateAgentProfile)
		admin.DELETE("/agent-profiles/:id", a.AdminDeleteAgentProfile)
		admin.POST("/agent-profiles/:id/avatar", a.AdminUploadAgentProfileAvatar)
		admin.GET("/llm-config", a.AdminGetLLMConfig)
		admin.PUT("/llm-config", a.AdminPutLLMConfig)
		admin.GET("/settings", a.AdminGetSettings)
		admin.PUT("/settings", a.AdminPutSettings)
		// Module 2: Player — chapters/bitrates admin
		admin.GET("/videos/:id/chapters", a.AdminListVideoChapters)
		admin.POST("/videos/:id/chapters", a.AdminCreateVideoChapter)
		admin.DELETE("/videos/:id/chapters/:chapterId", a.AdminDeleteVideoChapter)
		admin.GET("/videos/:id/bitrates", a.AdminListVideoBitrates)
		admin.POST("/videos/:id/bitrates", a.AdminCreateVideoBitrate)
		admin.DELETE("/videos/:id/bitrates/:bitrateId", a.AdminDeleteVideoBitrate)
		// Module 3: Subtitles admin
		admin.GET("/subtitles", a.AdminListSubtitles)
		admin.DELETE("/subtitles/:id", a.AdminDeleteSubtitle)
		// Module 13: Ticket / Work Order System
		admin.GET("/tickets", a.AdminListTickets)
		admin.GET("/tickets/:id", a.AdminGetTicket)
		admin.POST("/tickets/:id/assign", a.AdminAssignTicket)
		admin.POST("/tickets/:id/status", a.AdminUpdateTicketStatus)
		admin.POST("/tickets/:id/messages", a.AdminAddTicketMessage)
		admin.POST("/tickets/:id/close", a.AdminCloseTicket)
		admin.POST("/tickets/:id/reopen", a.AdminReopenTicket)
		// Module 14: Risk Control
		admin.GET("/risk/rules", a.AdminListRiskRules)
		admin.POST("/risk/rules", a.AdminCreateRiskRule)
		admin.PUT("/risk/rules/:id", a.AdminUpdateRiskRule)
		admin.DELETE("/risk/rules/:id", a.AdminDeleteRiskRule)
		admin.POST("/risk/rules/:id/toggle", a.AdminToggleRiskRule)
		admin.GET("/risk/bw-list", a.AdminListBWList)
		admin.POST("/risk/bw-list", a.AdminCreateBWEntry)
		admin.DELETE("/risk/bw-list/:id", a.AdminDeleteBWEntry)
		// Module 15: Copyright
		admin.GET("/copyright/complaints", a.AdminListCopyrightComplaints)
		admin.GET("/copyright/complaints/:id", a.AdminGetCopyrightComplaint)
		admin.POST("/copyright/complaints/:id/accept", a.AdminAcceptCopyrightComplaint)
		admin.POST("/copyright/complaints/:id/reject", a.AdminRejectCopyrightComplaint)
		admin.POST("/copyright/complaints/:id/takedown", a.AdminTakedownContent)
		admin.POST("/copyright/complaints/:id/restore", a.AdminRestoreContent)
		// Module 16: BI/Stats
		admin.GET("/bi/zone-stats", a.AdminGetZoneStats)
		admin.GET("/bi/creator-stats", a.AdminGetCreatorStats)
		admin.GET("/bi/time-series", a.AdminGetTimeSeries)
		admin.POST("/bi/export", a.AdminExportReport)
		admin.GET("/bi/reports", a.AdminListSavedReports)
		admin.POST("/bi/reports", a.AdminSaveReport)
		admin.DELETE("/bi/reports/:id", a.AdminDeleteSavedReport)
		// Module 17: Customer Service
		admin.GET("/cs/conversations", a.AdminListCSConversations)
		admin.GET("/cs/conversations/:id", a.AdminGetCSConversation)
		admin.POST("/cs/conversations/:id/assign", a.AdminAssignCSConversation)
		admin.POST("/cs/conversations/:id/messages", a.AdminSendCSMessage)
		admin.POST("/cs/conversations/:id/close", a.AdminCloseCSConversation)
		admin.GET("/cs/templates", a.AdminListCSTemplates)
		admin.POST("/cs/templates", a.AdminCreateCSTemplate)
		admin.PUT("/cs/templates/:id", a.AdminUpdateCSTemplate)
		admin.DELETE("/cs/templates/:id", a.AdminDeleteCSTemplate)
		// Module 4: Comment reports admin
		admin.GET("/comment-reports", a.AdminListCommentReports)
		admin.POST("/comment-reports/:id/handle", a.AdminHandleCommentReport)
		// Module 18-22: Ops — Queue/Tasks/Monitoring/Trace/CDN
		admin.GET("/ops/tasks", a.AdminListTaskLogs)
		admin.POST("/ops/tasks/:id/retry", a.AdminRetryTask)
		admin.GET("/ops/queue-stats", a.AdminGetQueueStats)
		admin.GET("/ops/alert-rules", a.AdminListAlertRules)
		admin.POST("/ops/alert-rules", a.AdminCreateAlertRule)
		admin.PUT("/ops/alert-rules/:id", a.AdminUpdateAlertRule)
		admin.DELETE("/ops/alert-rules/:id", a.AdminDeleteAlertRule)
		admin.POST("/ops/alert-rules/:id/toggle", a.AdminToggleAlertRule)
		admin.GET("/ops/alert-records", a.AdminListAlertRecords)
		admin.POST("/ops/alert-records/:id/ack", a.AdminAckAlert)
		admin.GET("/ops/health", a.AdminGetSystemHealth)
		admin.GET("/ops/traces", a.AdminSearchTraces)
		admin.GET("/ops/traces/:id", a.AdminGetTrace)
		admin.POST("/ops/cdn/refresh", a.AdminCreateCDNRefresh)
		admin.GET("/ops/cdn/refresh", a.AdminListCDNRefreshTasks)
		admin.GET("/ops/oss/lifecycle", a.AdminListOSSLifecycleRules)
		admin.POST("/ops/oss/lifecycle", a.AdminCreateOSSLifecycleRule)
		admin.DELETE("/ops/oss/lifecycle/:id", a.AdminDeleteOSSLifecycleRule)
		// Module 21: Config — Feature Flags & Releases
		admin.GET("/config/feature-flags", a.AdminListFeatureFlags)
		admin.POST("/config/feature-flags", a.AdminCreateFeatureFlag)
		admin.PUT("/config/feature-flags/:id", a.AdminUpdateFeatureFlag)
		admin.POST("/config/feature-flags/:id/toggle", a.AdminToggleFeatureFlag)
		admin.GET("/config/releases", a.AdminListReleases)
		admin.POST("/config/releases", a.AdminCreateRelease)
		admin.POST("/config/releases/:id/rollback", a.AdminRollbackRelease)
		// Module 23: RBAC & Audit
		admin.GET("/rbac/roles", a.AdminListRoles)
		admin.POST("/rbac/roles", a.AdminCreateRole)
		admin.PUT("/rbac/roles/:id", a.AdminUpdateRole)
		admin.GET("/rbac/roles/:id", a.AdminGetRolePermissions)
		admin.DELETE("/rbac/roles/:id", a.AdminDeleteRole)
		admin.GET("/rbac/permissions", a.AdminListPermissions)
		admin.POST("/rbac/roles/:id/permissions", a.AdminAssignRolePermissions)
		admin.GET("/rbac/roles/:id/permissions", a.AdminGetRolePermissions)
		admin.POST("/rbac/admins/:adminId/role", a.AdminAssignAdminRole)
		admin.GET("/rbac/admins/:adminId/role", a.AdminGetAdminRole)
		admin.GET("/rbac/admins", a.AdminListAdmins)
		admin.POST("/rbac/admins", a.AdminCreateAdmin)
		admin.GET("/rbac/audit-logs", a.AdminListAuditLogs)
		admin.GET("/rbac/audit-logs/:id", a.AdminGetAuditLog)
		admin.GET("/rbac/login-logs", a.AdminListLoginLogs)
		admin.GET("/risk/hits", a.AdminListRiskHitLogs)
		admin.POST("/rbac/approval-flows", a.AdminCreateApprovalFlow)
		admin.POST("/rbac/approval-flows/:id/approve", a.AdminApproveFlowStep)
		admin.POST("/rbac/approval-flows/:id/reject", a.AdminRejectFlowStep)
		admin.GET("/rbac/approval-flows", a.AdminListApprovalFlows)
		// Module 9: Special Pages & Campaigns
		admin.GET("/specials", a.AdminListSpecialPages)
		admin.POST("/specials", a.AdminCreateSpecialPage)
		admin.PUT("/specials/:id", a.AdminUpdateSpecialPage)
		admin.DELETE("/specials/:id", a.AdminDeleteSpecialPage)
		admin.GET("/campaigns", a.AdminListCampaigns)
		admin.POST("/campaigns", a.AdminCreateCampaign)
		admin.PUT("/campaigns/:id", a.AdminUpdateCampaign)
		admin.DELETE("/campaigns/:id", a.AdminDeleteCampaign)
	}

	authd := r.Group("/api/v1")
	authd.Use(middleware.JWTAuth(jwtm))
	{
		authd.GET("/users/me", a.GetMe)
		authd.GET("/users/me/daily-rewards", a.GetMeDailyRewards)
		authd.GET("/users/me/coin-ledger", a.ListMeCoinLedger)
		authd.GET("/users/me/view-history", a.ListMyViewHistory)
		authd.DELETE("/users/me/view-history", a.ClearMyViewHistory)
		authd.DELETE("/users/me/view-history/:videoId", a.DeleteMyViewHistoryEntry)
		authd.DELETE("/users/me/view-history/articles/:articleId", a.DeleteMyArticleViewHistoryEntry)
		authd.GET("/users/me/view-history/settings", a.GetMyViewHistorySettings)
		authd.PUT("/users/me/view-history/settings", a.PutMyViewHistorySettings)
		authd.POST("/videos/:id/view-history", a.PostVideoViewHistory)
		authd.POST("/users/me/daily-rewards/watch", a.PostMeDailyRewardWatch)
		authd.PUT("/users/me", a.UpdateMeUsername)
		authd.PUT("/users/me/profile", a.UpdateMeProfile)
		authd.PUT("/users/me/announcement", a.UpdateMeAnnouncement)
		authd.GET("/users/me/space-privacy", a.GetMeSpacePrivacy)
		authd.PUT("/users/me/space-privacy", a.UpdateMeSpacePrivacy)
		authd.POST("/users/:userId/follow", a.ToggleFollowUser)
		authd.POST("/users/:userId/block", a.BlockUser)
		authd.GET("/users/me/follow-groups", a.ListMyFollowGroups)
		authd.POST("/users/me/follow-groups", a.CreateFollowGroup)
		authd.PUT("/users/me/follow-groups/:groupId", a.UpdateFollowGroup)
		authd.DELETE("/users/me/follow-groups/:groupId", a.DeleteFollowGroup)
		authd.GET("/users/me/following/:followeeId/groups", a.ListFolloweeGroupIDs)
		authd.POST("/users/me/follow-groups/:groupId/members", a.AddFollowGroupMember)
		authd.DELETE("/users/me/follow-groups/:groupId/members/:followeeId", a.RemoveFollowGroupMember)
		authd.PUT("/users/me/password", a.UpdateMePassword)
		authd.POST("/users/me/deletion/request", a.RequestAccountDeletion)
		authd.POST("/users/me/deletion/revoke", a.RevokeAccountDeletion)
		authd.POST("/users/me/avatar", a.UpdateMeAvatar)
		authd.GET("/users/me/dynamics", a.ListMyDynamics)
		authd.POST("/users/me/dynamics", a.PostUserDynamic)
		authd.PUT("/users/me/dynamics/:id", a.PutMyUserDynamic)
		authd.DELETE("/users/me/dynamics/:id", a.DeleteMyDynamic)
		authd.PATCH("/users/me/dynamics/:id/playback", a.PatchUserDynamicPlayback)
		authd.POST("/user-dynamics/:id/comments", a.PostDynamicComment)
		authd.POST("/user-dynamics/:id/like", a.ToggleDynamicLike)
		authd.DELETE("/dynamic-comments/:id", a.DeleteDynamicComment)
		authd.POST("/dynamic-comments/:id/like", a.ToggleDynamicCommentLike)
		authd.POST("/dynamic-comments/:id/dislike", a.ToggleDynamicCommentDislike)
		authd.POST("/dynamic-comments/:id/approve", a.ApproveDynamicComment)
		authd.POST("/dynamic-comments/:id/ignore-curated", a.IgnoreCuratedDynamicComment)
		authd.GET("/users/me/videos", a.ListMyVideos)
		authd.POST("/articles", a.PostArticle)
		authd.GET("/users/me/articles", a.ListMyArticles)
		authd.GET("/users/me/articles/:id", a.GetMyArticle)
		authd.PUT("/users/me/articles/:id", a.PutMyArticle)
		authd.PATCH("/users/me/articles/:id/playback", a.PatchArticlePlayback)
		authd.PUT("/users/me/articles/:id/cover", a.UpdateArticleCover)
		authd.DELETE("/users/me/articles/:id", a.DeleteMyArticle)
		authd.GET("/users/me/article-favorites", a.ListMyArticleFavorites)
		authd.POST("/articles/:id/view", a.PostArticleView)
		authd.POST("/articles/:id/favorite", a.ToggleArticleFavorite)
		authd.POST("/articles/:id/coin", a.PostArticleCoin)
		authd.POST("/articles/:id/comments", a.PostArticleComment)
		authd.POST("/article-comments/:id/like", a.ToggleArticleCommentLike)
		authd.POST("/article-comments/:id/dislike", a.ToggleArticleCommentDislike)
		authd.POST("/article-comments/:id/pin", a.PinArticleComment)
		authd.POST("/article-comments/:id/approve", a.ApproveArticleComment)
		authd.POST("/article-comments/:id/ignore-curated", a.IgnoreCuratedArticleComment)
		authd.DELETE("/article-comments/:id", a.DeleteArticleComment)
		authd.GET("/users/me/creator/comments", a.ListCreatorComments)
		authd.GET("/users/me/creator/danmakus", a.ListCreatorDanmakus)
		authd.DELETE("/danmakus/:id", a.DeleteDanmaku)
		authd.POST("/danmakus/:id/like", a.ToggleDanmakuLike)
		authd.DELETE("/videos/:id", a.DeleteMyVideo)
		authd.POST("/videos", a.UploadVideo)
		authd.POST("/videos/draft", a.SaveVideoDraft)
		authd.PUT("/videos/:id/draft", a.UpdateVideoDraft)
		authd.POST("/videos/:id/draft", a.UpdateVideoDraft)
		authd.POST("/videos/:id/publish", a.PublishVideoDraft)
		authd.POST("/videos/:id/replace-media", a.ReplaceVideoMedia)
		authd.GET("/users/me/videos/:id/draft-source", a.GetMyVideoDraftSource)
		authd.PUT("/videos/:id/cover", a.UpdateVideoCover)
		authd.PUT("/videos/:id", a.UpdateMyVideo)
		authd.PATCH("/videos/:id/playback", a.PatchVideoPlayback)
		authd.POST("/videos/:id/like", a.ToggleVideoLike)
		authd.POST("/videos/:id/favorite", a.ToggleVideoFavorite)
		authd.GET("/videos/:id/favorite-picker", a.GetVideoFavoritePicker)
		authd.PUT("/videos/:id/favorite-folders", a.SetVideoFavoriteFolders)
		authd.PUT("/videos/:id/favorite-folders/move", a.MoveVideoFavoriteFolder)
		authd.POST("/videos/:id/favorite-folders/:folderId", a.AddVideoToFavoriteFolder)
		authd.DELETE("/videos/:id/favorite-folders/:folderId", a.RemoveVideoFromFavoriteFolder)
		authd.POST("/videos/:id/coin", a.PostVideoCoin)
		authd.POST("/videos/:id/watch-later", a.ToggleWatchLater)
		authd.GET("/users/me/favorites", a.ListMyFavorites)
		authd.GET("/users/me/favorite-folders", a.ListMyFavoriteFolders)
		authd.POST("/users/me/favorite-folders", a.CreateFavoriteFolder)
		authd.PUT("/users/me/favorite-folders/:folderId", a.UpdateFavoriteFolder)
		authd.DELETE("/users/me/favorite-folders/:folderId", a.DeleteFavoriteFolder)
		authd.DELETE("/users/me/favorite-folders/:folderId/invalid-favorites", a.ClearInvalidFavoritesInFolder)
		authd.POST("/users/me/favorite-folders/:folderId/batch-remove", a.BatchRemoveVideosFromFavoriteFolder)
		authd.GET("/users/me/search-history", a.GetMySearchHistory)
		authd.PUT("/users/me/search-history", a.PutMySearchHistory)
		authd.POST("/users/me/search-history", a.PostMySearchHistory)
		authd.GET("/users/me/watch-later", a.ListMyWatchLater)
		authd.DELETE("/users/me/watch-later", a.ClearMyWatchLater)
		authd.DELETE("/users/me/watch-later/watched", a.ClearWatchedWatchLater)
		authd.POST("/users/me/watch-later/:id/watched", a.MarkWatchLaterWatched)
		authd.POST("/videos/:id/danmaku", a.PostDanmaku)
		authd.POST("/videos/:id/comments", a.PostComment)
		authd.DELETE("/comments/:id", a.DeleteComment)
		authd.POST("/comments/:id/pin", a.PinComment)
		authd.POST("/comments/:id/approve", a.ApproveComment)
		authd.POST("/comments/:id/ignore-curated", a.IgnoreCuratedComment)
		authd.POST("/comments/:id/like", a.ToggleLike)
		authd.POST("/comments/:id/dislike", a.ToggleDislike)
		authd.GET("/notifications/unread-summary", a.UnreadSummary)
		authd.GET("/notifications", a.ListNotifications)
		authd.GET("/notifications/:id/like-likers", a.ListNotificationLikeLikers)
		authd.PATCH("/notifications/read-by-category", a.MarkNotificationCategoryRead)
		authd.PATCH("/notifications/read-batch", a.MarkNotificationsReadBatch)
		authd.PATCH("/notifications/:id/read", a.MarkNotificationRead)
		authd.POST("/notifications/:id/mute-likes", a.MuteLikeNotification)
		authd.POST("/notifications/:id/comment-like", a.ToggleNotificationCommentLike)
		authd.POST("/notifications/:id/comment-reply", a.PostNotificationCommentReply)
		authd.DELETE("/notifications/:id", a.DeleteNotification)
		authd.GET("/dm/conversations", a.ListDmConversations)
		authd.POST("/dm/conversations", a.CreateDmConversation)
		authd.DELETE("/dm/conversations/:id", a.DeleteDmConversation)
		authd.POST("/dm/conversations/:id/reset", a.ResetDmAgentConversation)
		authd.PATCH("/dm/conversations/:id/settings", a.PatchDmConversationSettings)
		authd.GET("/dm/conversations/:id/messages", a.ListDmMessages)
		authd.POST("/dm/conversations/:id/messages", a.PostDmMessage)
		authd.POST("/reports", a.PostReport)
		// Module 3: Subtitle upload/delete (auth)
		authd.POST("/videos/:id/subtitles", a.UploadSubtitle)
		authd.DELETE("/videos/:id/subtitles/:subtitleId", a.DeleteSubtitle)
		// Module 4: Comment enhancement (auth)
		authd.POST("/videos/:id/comments-with-image", a.PostCommentWithImage)
		authd.POST("/comments/:id/images", a.UploadCommentImage)
		authd.DELETE("/comments/:id/images/:imageId", a.DeleteCommentImage)
		authd.GET("/comments/:id/images", a.ListCommentImages)
		authd.GET("/videos/:id/comments/config", a.GetCommentSortOptions)
		authd.POST("/comments/:id/report", a.ReportComment)
		// Module 5: Creator center (auth)
		authd.POST("/videos/:id/schedule", a.SchedulePublish)
		authd.DELETE("/videos/:id/schedule", a.CancelSchedule)
		authd.GET("/users/me/creator/stats", a.GetCreatorStats)
		authd.GET("/users/me/creator/video-stats", a.GetCreatorVideoStats)
		// Creator chapter management (auth, ownership check)
		authd.POST("/videos/:id/chapters", a.CreatorCreateChapter)
		authd.DELETE("/videos/:id/chapters/:chapterId", a.CreatorDeleteChapter)
		// Module 7: Subscription feed (auth)
		authd.GET("/feed/subscription", a.GetSubscriptionFeed)
		// Module 13: Tickets (auth)
		authd.POST("/tickets", a.PostTicket)
		authd.GET("/users/me/tickets", a.ListMyTickets)
		authd.GET("/users/me/tickets/:id", a.GetMyTicket)
		authd.POST("/users/me/tickets/:id/messages", a.AddTicketMessageByUser)
		authd.POST("/users/me/tickets/:id/appeal", a.AppealTicket)
		// Module 15: Copyright (auth)
		authd.POST("/copyright/complaints", a.PostCopyrightComplaint)
		authd.GET("/users/me/copyright/complaints", a.ListMyCopyrightComplaints)
		// Module 17: Customer Service (auth)
		authd.POST("/cs/conversations", a.PostCSConversation)
		authd.GET("/users/me/cs/conversations", a.ListMyCSConversations)
		authd.GET("/users/me/cs/conversations/:id", a.GetMyCSConversation)
		authd.POST("/users/me/cs/conversations/:id/messages", a.SendCSMessageByUser)
	}

	r.GET("/api/v1/ws/danmaku", a.ServeDanmaku)
	r.GET("/api/v1/ws/chat", a.ServeChat)
}

func corsMiddleware(c *gin.Context) {
	h := c.Writer.Header()
	h.Set("Access-Control-Allow-Origin", "*")
	h.Set("Access-Control-Allow-Methods", "GET, POST, PUT, PATCH, DELETE, OPTIONS")
	h.Set("Access-Control-Allow-Headers", "Authorization, Content-Type")
	if c.Request.Method == http.MethodOptions {
		c.AbortWithStatus(http.StatusNoContent)
		return
	}
	c.Next()
}
