package handler

import (
	"net/http"
	"os"

	"github.com/gin-gonic/gin"

	"minibili/internal/logger"
	"minibili/internal/middleware"
	"minibili/internal/pkg/jwttoken"
)

// RegisterRoutes wires HTTP and WebSocket routes.
func RegisterRoutes(r *gin.Engine, a *API, jwtm *jwttoken.Manager) {
	r.Use(corsMiddleware)
	r.Use(logger.GinMiddleware(a.Log))
	r.Use(middleware.TraceRecordMiddleware(a.DB))

	r.GET("/api/v1/health", a.Health)

	// ─── NocoBase Bridge: Internal API for NocoBase → Go actions ───
	nb := r.Group("/api/v1/internal")
	nb.Use(func(c *gin.Context) {
		apiKey := c.GetHeader("X-Internal-API-Key")
		if apiKey == "" || apiKey != os.Getenv("NOCOBASE_API_KEY") {
			c.AbortWithStatusJSON(http.StatusUnauthorized, gin.H{"code": 40100, "msg": "internal auth required"})
			return
		}
		c.Next()
	})
	{
		nb.POST("/takedown/video/:id", a.NocoBaseTakedownVideo)
		nb.POST("/restore/video/:id", a.NocoBaseRestoreVideo)
		nb.POST("/ban/user/:id", a.NocoBaseBanUser)
		nb.POST("/unban/user/:id", a.NocoBaseUnbanUser)
		nb.GET("/user/:id", a.NocoBaseGetUserInfo)
		nb.GET("/video/:id", a.NocoBaseGetVideoInfo)
		nb.POST("/nocobase-webhook", a.NocoBaseWebhook)
	}

	pub := r.Group("/api/v1")
	{
		pub.POST("/users", a.Register)
		pub.POST("/auth/login", a.Login)
		pub.POST("/auth/refresh", a.Refresh)
		pub.GET("/videos", middleware.OptionalJWT(jwtm), a.ListPublishedVideos)
		pub.GET("/space/:userId", middleware.OptionalJWT(jwtm), a.GetUserPublic)
		pub.GET("/space/:userId/videos", middleware.OptionalJWT(jwtm), a.ListUserPublishedVideos)
		pub.GET("/space/:userId/favorites", middleware.OptionalJWT(jwtm), a.ListUserFavorites)
		pub.GET("/space/:userId/favorite-folders", middleware.OptionalJWT(jwtm), a.ListUserFavoriteFolders)
		pub.GET("/space/:userId/recent-coins", middleware.OptionalJWT(jwtm), a.ListUserRecentCoinVideos)
		pub.GET("/space/:userId/following", middleware.OptionalJWT(jwtm), a.ListUserFollowing)
		pub.GET("/space/:userId/followers", middleware.OptionalJWT(jwtm), a.ListUserFollowers)
		pub.GET("/videos/:id", middleware.OptionalJWT(jwtm), a.GetVideo)
		pub.GET("/videos/:id/comments", middleware.OptionalJWT(jwtm), a.ListComments)
		pub.GET("/articles/:id", middleware.OptionalJWT(jwtm), a.GetArticle)
		pub.GET("/articles", middleware.OptionalJWT(jwtm), a.ListPublishedArticles)
		pub.GET("/online", a.GetOnlineCount)
		pub.GET("/articles/:id/comments", middleware.OptionalJWT(jwtm), a.ListArticleComments)
		pub.GET("/space/:userId/articles", middleware.OptionalJWT(jwtm), a.ListUserPublishedArticles)
		pub.GET("/space/:userId/dynamics", middleware.OptionalJWT(jwtm), a.ListUserPublishedDynamics)
		pub.GET("/user-dynamics/:id", middleware.OptionalJWT(jwtm), a.GetUserDynamic)
		pub.GET("/user-dynamics/:id/comments", middleware.OptionalJWT(jwtm), a.ListDynamicComments)
		pub.GET("/space/:userId/article-favorites", middleware.OptionalJWT(jwtm), a.ListUserArticleFavorites)
		pub.GET("/stats/home", a.HomeStats)
		pub.GET("/hot-search", a.HotSearchList)
		pub.GET("/home-banners", a.ListHomeBanners)
		pub.GET("/search", a.SearchAll)
		pub.GET("/search/suggest", middleware.OptionalJWT(jwtm), a.SearchSuggest)
		// Module 2: Player chapters/bitrates (public)
		pub.GET("/videos/:id/chapters", a.ListVideoChapters)
		pub.GET("/videos/:id/bitrates", a.ListVideoBitrates)
		// Module 3: Subtitles (public list)
		pub.GET("/videos/:id/subtitles", a.ListSubtitles)
		pub.GET("/videos/:id/subtitles/:subtitleId", a.GetSubtitle)
		// Module 7: Feed & Ranking (public)
		pub.GET("/feed/recommendation", a.GetRecommendationFeed)
		pub.GET("/leaderboard", a.GetLeaderboard)
		pub.GET("/zones/:zone/recommendation", a.GetZoneRecommendation)
		// Module 21: Feature flag check (public)
		pub.GET("/config/feature-flags/:key", a.AdminCheckFeatureFlag)
		// Module 9: Special pages (public)
		pub.GET("/specials", a.ListPublicSpecialPages)
		pub.GET("/specials/:slug", a.GetPublicSpecialPage)
		// Live: public
		pub.GET("/live/rooms", a.ListLiveRooms)
		pub.GET("/live/room/my", middleware.OptionalJWT(jwtm), a.GetOrCreateMyLiveRoom)
		pub.GET("/live/room/:id", a.GetLiveRoom)

		pub.POST("/admin/auth/login", a.AdminLogin)
		pub.POST("/admin/auth/refresh", a.AdminRefresh)
	}

	admin := r.Group("/api/v1/admin")
	admin.Use(middleware.AdminJWTAuth(jwtm))
	{
		// Read-only (all authenticated admins)
		admin.GET("/me", a.AdminMe)
		admin.GET("/users", a.AdminListUsers)
		admin.GET("/users/:id", a.AdminGetUser)
		admin.GET("/users/:id/violations", a.AdminGetUserViolations)
		admin.GET("/home-banners", a.AdminListBanners)
		admin.GET("/videos", a.AdminListVideos)
		admin.GET("/videos/:id", a.AdminGetVideo)
		admin.GET("/comments", a.AdminListComments)
		admin.GET("/comments/:id", a.AdminGetComment)
		admin.GET("/reports", a.AdminListReports)
		admin.GET("/dashboard", a.AdminDashboard)
		admin.GET("/articles", a.AdminListArticles)
		admin.GET("/articles/:id", a.AdminGetArticle)
		admin.GET("/dynamics", a.AdminListDynamics)
		admin.GET("/dynamics/:id", a.AdminGetDynamic)

		// BI read-only (all authenticated admins — no special permission needed)
		admin.GET("/bi/summary", a.AdminGetBISummary)
		admin.GET("/bi/article-stats", a.AdminGetArticleStats)
		admin.GET("/bi/engagement-stats", a.AdminGetEngagementStats)
		admin.GET("/bi/manuscript-stats", a.AdminGetManuscriptStats)
		admin.GET("/bi/zone-stats", a.AdminGetZoneStats)
		admin.GET("/bi/creator-stats", a.AdminGetCreatorStats)
		admin.GET("/bi/time-series", a.AdminGetTimeSeries)
		admin.GET("/bi/reports", a.AdminListSavedReports)

		// BI write — requires dashboard:export
		biOps := admin.Group("", middleware.RequirePermission(a.DB, "dashboard", "export"))
		biOps.POST("/bi/reports", a.AdminSaveReport)
		biOps.DELETE("/bi/reports/:id", a.AdminDeleteSavedReport)
		biOps.POST("/bi/export", a.AdminExportReport)

		// Permission-protected: user.ban
		userOps := admin.Group("", middleware.RequirePermission(a.DB, "user", "ban"))
		userOps.POST("/users/:id/ban", a.AdminBanUser)
		userOps.POST("/users/:id/unban", a.AdminUnbanUser)
		userOps.POST("/users/:id/delete", a.AdminDeleteUser)

		// Permission-protected: video.delete
		vOps := admin.Group("", middleware.RequirePermission(a.DB, "video", "approve"))
		vOps.POST("/videos/:id/approve", a.AdminApproveVideo)
		vOps.POST("/videos/:id/reject", a.AdminRejectVideo)
		vOps.POST("/videos/:id/delete", a.AdminDeleteVideo)
		vOps.DELETE("/videos/:id", a.AdminDeleteVideo)
		vOps.POST("/videos/batch-approve", a.AdminBatchApproveVideos)

		// Permission-protected: comment.delete
		cOps := admin.Group("", middleware.RequirePermission(a.DB, "comment", "delete"))
		cOps.POST("/comments/:id/delete", a.AdminDeleteComment)
		cOps.DELETE("/comments/:id", a.AdminDeleteComment)

		// Permission-protected: ticket.handle (reports)
		rOps := admin.Group("", middleware.RequirePermission(a.DB, "ticket", "handle"))
		rOps.POST("/reports/:id/handle", a.AdminHandleReport)
		rOps.POST("/reports/batch", a.AdminBatchHandleReports)
		rOps.DELETE("/reports/:id", a.AdminDeleteReport)

		// Permission-protected: article.approve
		aOps := admin.Group("", middleware.RequirePermission(a.DB, "article", "approve"))
		aOps.POST("/articles/:id/approve", a.AdminApproveArticle)
		aOps.POST("/articles/:id/reject", a.AdminRejectArticle)
		aOps.POST("/articles/:id/delete", a.AdminDeleteArticle)
		aOps.DELETE("/articles/:id", a.AdminDeleteArticle)

		// Permission-protected: dynamic.manage
		dynOps := admin.Group("", middleware.RequirePermission(a.DB, "dynamic", "manage"))
		dynOps.POST("/dynamics/:id/delete", a.AdminDeleteDynamic)
		dynOps.DELETE("/dynamics/:id", a.AdminDeleteDynamic)

		// Permission-protected: banner.manage
		banOps := admin.Group("", middleware.RequirePermission(a.DB, "banner", "manage"))
		banOps.POST("/home-banners", a.AdminCreateBanner)
		banOps.POST("/home-banners/upload-image", a.AdminUploadBannerImage)
		banOps.POST("/home-banners/:id/image", a.AdminUploadBannerImageByID)
		banOps.PUT("/home-banners/:id", a.AdminUpdateBanner)
		banOps.DELETE("/home-banners/:id", a.AdminDeleteBanner)

		// Permission-protected: hotsearch.manage
		hsOps := admin.Group("", middleware.RequirePermission(a.DB, "hotsearch", "manage"))
		hsOps.GET("/hot-search/ops", a.AdminListHotSearchOps)
		hsOps.GET("/hot-search/dashboard", a.AdminHotSearchDashboard)
		hsOps.GET("/hot-search/preview", a.AdminPreviewHotSearch)
		hsOps.POST("/hot-search/ops", a.AdminCreateHotSearchOp)
		hsOps.POST("/hot-search/quick-op", a.AdminQuickHotSearchOp)
		hsOps.POST("/hot-search/reorder", a.AdminReorderHotSearch)
		hsOps.POST("/hot-search/display-order/reset", a.AdminResetHotSearchDisplayOrder)
		hsOps.POST("/hot-search/redis/remove", a.AdminRemoveHotSearchRedis)
		hsOps.POST("/hot-search/redis/boost", a.AdminBoostHotSearchRedis)
		hsOps.PUT("/hot-search/ops/:id", a.AdminUpdateHotSearchOp)
		hsOps.DELETE("/hot-search/ops/:id", a.AdminDeleteHotSearchOp)

		// Permission-protected: agent.manage
		agOps := admin.Group("", middleware.RequirePermission(a.DB, "agent", "manage"))
		agOps.GET("/agent-settings", a.AdminGetAgentSettings)
		agOps.PUT("/agent-settings", a.AdminPutAgentSettings)
		agOps.POST("/agent-settings/avatar", a.AdminUploadAgentAvatar)
		agOps.GET("/agent-profiles", a.AdminListAgentProfiles)
		agOps.POST("/agent-profiles", a.AdminCreateAgentProfile)
		agOps.PUT("/agent-profiles/:id", a.AdminUpdateAgentProfile)
		agOps.DELETE("/agent-profiles/:id", a.AdminDeleteAgentProfile)
		agOps.POST("/agent-profiles/:id/avatar", a.AdminUploadAgentProfileAvatar)

		// Permission-protected: setting.manage (covers LLM config + system settings)
		setOps := admin.Group("", middleware.RequirePermission(a.DB, "setting", "manage"))
		setOps.GET("/llm-config", a.AdminGetLLMConfig)
		setOps.PUT("/llm-config", a.AdminPutLLMConfig)
		setOps.GET("/settings", a.AdminGetSettings)
		setOps.PUT("/settings", a.AdminPutSettings)

		// Permission-protected: video.approve (player chapters/bitrates admin)
		chOps := admin.Group("", middleware.RequirePermission(a.DB, "video", "approve"))
		chOps.GET("/videos/:id/chapters", a.AdminListVideoChapters)
		chOps.POST("/videos/:id/chapters", a.AdminCreateVideoChapter)
		chOps.DELETE("/videos/:id/chapters/:chapterId", a.AdminDeleteVideoChapter)
		chOps.GET("/videos/:id/bitrates", a.AdminListVideoBitrates)
		chOps.POST("/videos/:id/bitrates", a.AdminCreateVideoBitrate)
		chOps.DELETE("/videos/:id/bitrates/:bitrateId", a.AdminDeleteVideoBitrate)

		// Permission-protected: subtitle.manage
		subOps := admin.Group("", middleware.RequirePermission(a.DB, "subtitle", "manage"))
		subOps.GET("/subtitles", a.AdminListSubtitles)
		subOps.POST("/subtitles", a.AdminCreateSubtitle)
		subOps.PUT("/subtitles/:id", a.AdminUpdateSubtitle)
		subOps.DELETE("/subtitles/:id", a.AdminDeleteSubtitle)

		// Permission-protected: ticket.handle
		ticketOps := admin.Group("", middleware.RequirePermission(a.DB, "ticket", "handle"))
		ticketOps.GET("/tickets", a.AdminListTickets)
		ticketOps.GET("/tickets/:id", a.AdminGetTicket)
		ticketOps.POST("/tickets/:id/assign", a.AdminAssignTicket)
		ticketOps.POST("/tickets/:id/status", a.AdminUpdateTicketStatus)
		ticketOps.POST("/tickets/:id/messages", a.AdminAddTicketMessage)
		ticketOps.POST("/tickets/:id/auto-assign", a.AdminAutoAssignTicket)
		ticketOps.POST("/tickets/:id/close", a.AdminCloseTicket)
		ticketOps.POST("/tickets/:id/reopen", a.AdminReopenTicket)
		ticketOps.GET("/tickets/satisfaction-stats", a.AdminGetSatisfactionStats)
		ticketOps.GET("/tickets/stats", a.AdminGetTicketStats)

		// Permission-protected: risk.manage
		riskOps := admin.Group("", middleware.RequirePermission(a.DB, "risk", "manage"))
		riskOps.GET("/risk/rules", a.AdminListRiskRules)
		riskOps.POST("/risk/rules", a.AdminCreateRiskRule)
		riskOps.PUT("/risk/rules/:id", a.AdminUpdateRiskRule)
		riskOps.DELETE("/risk/rules/:id", a.AdminDeleteRiskRule)
		riskOps.POST("/risk/rules/:id/toggle", a.AdminToggleRiskRule)
		riskOps.GET("/risk/bw-list", a.AdminListBWList)
		riskOps.POST("/risk/bw-list", a.AdminCreateBWEntry)
		riskOps.DELETE("/risk/bw-list/:id", a.AdminDeleteBWEntry)
		riskOps.GET("/risk/hits", a.AdminListRiskHitLogs)
		riskOps.GET("/risk/stats", a.AdminGetRiskStats)

		// Permission-protected: copyright.handle
		crOps := admin.Group("", middleware.RequirePermission(a.DB, "copyright", "handle"))
		crOps.GET("/copyright/complaints", a.AdminListCopyrightComplaints)
		crOps.GET("/copyright/complaints/:id", a.AdminGetCopyrightComplaint)
		crOps.POST("/copyright/complaints/:id/accept", a.AdminAcceptCopyrightComplaint)
		crOps.POST("/copyright/complaints/:id/reject", a.AdminRejectCopyrightComplaint)
		crOps.POST("/copyright/complaints/:id/takedown", a.AdminTakedownContent)
		crOps.POST("/copyright/complaints/:id/restore", a.AdminRestoreContent)

		// Permission-protected: cs.manage
		cusOps := admin.Group("", middleware.RequirePermission(a.DB, "cs", "manage"))
		cusOps.GET("/cs/conversations", a.AdminListCSConversations)
		cusOps.GET("/cs/conversations/:id", a.AdminGetCSConversation)
		cusOps.POST("/cs/conversations/:id/assign", a.AdminAssignCSConversation)
		cusOps.POST("/cs/conversations/:id/messages", a.AdminSendCSMessage)
		cusOps.POST("/cs/conversations/:id/close", a.AdminCloseCSConversation)
		cusOps.GET("/cs/templates", a.AdminListCSTemplates)
		cusOps.POST("/cs/templates", a.AdminCreateCSTemplate)
		cusOps.PUT("/cs/templates/:id", a.AdminUpdateCSTemplate)
		cusOps.DELETE("/cs/templates/:id", a.AdminDeleteCSTemplate)

		// Permission-protected: comment.delete (comment reports admin)
		cmrOps := admin.Group("", middleware.RequirePermission(a.DB, "comment", "delete"))
		cmrOps.GET("/comment-reports", a.AdminListCommentReports)
		cmrOps.POST("/comment-reports/:id/handle", a.AdminHandleCommentReport)

		// Permission-protected: ops.manage
		opsOps := admin.Group("", middleware.RequirePermission(a.DB, "ops", "manage"))
		opsOps.GET("/ops/tasks", a.AdminListTaskLogs)
		opsOps.POST("/ops/tasks/:id/retry", a.AdminRetryTask)
		opsOps.GET("/ops/queue-stats", a.AdminGetQueueStats)
		opsOps.GET("/ops/alert-rules", a.AdminListAlertRules)
		opsOps.POST("/ops/alert-rules", a.AdminCreateAlertRule)
		opsOps.PUT("/ops/alert-rules/:id", a.AdminUpdateAlertRule)
		opsOps.DELETE("/ops/alert-rules/:id", a.AdminDeleteAlertRule)
		opsOps.POST("/ops/alert-rules/:id/toggle", a.AdminToggleAlertRule)
		opsOps.GET("/ops/alert-records", a.AdminListAlertRecords)
		opsOps.POST("/ops/alert-records/:id/ack", a.AdminAckAlert)
		opsOps.POST("/ops/alerts/evaluate", a.AdminEvaluateAlerts)
		opsOps.POST("/ops/sync/trigger", a.AdminTriggerSync)
		opsOps.GET("/ops/health", a.AdminGetSystemHealth)
		opsOps.GET("/ops/traces", a.AdminSearchTraces)
		opsOps.GET("/ops/traces/:id", a.AdminGetTrace)
		opsOps.POST("/ops/cdn/refresh", a.AdminCreateCDNRefresh)
		opsOps.GET("/ops/cdn/refresh", a.AdminListCDNRefreshTasks)
		opsOps.GET("/ops/storage/lifecycle-rules", a.AdminListOSSLifecycleRules)
		opsOps.POST("/ops/storage/lifecycle-rules", a.AdminCreateOSSLifecycleRule)
		opsOps.PUT("/ops/storage/lifecycle-rules/:id", a.AdminUpdateOSSLifecycleRule)
		opsOps.DELETE("/ops/storage/lifecycle-rules/:id", a.AdminDeleteOSSLifecycleRule)

		// Permission-protected: config.manage
		cfgOps := admin.Group("", middleware.RequirePermission(a.DB, "config", "manage"))
		cfgOps.GET("/config/feature-flags", a.AdminListFeatureFlags)
		cfgOps.POST("/config/feature-flags", a.AdminCreateFeatureFlag)
		cfgOps.PUT("/config/feature-flags/:id", a.AdminUpdateFeatureFlag)
		cfgOps.DELETE("/config/feature-flags/:id", a.AdminDeleteFeatureFlag)
		cfgOps.POST("/config/feature-flags/:id/toggle", a.AdminToggleFeatureFlag)
		cfgOps.GET("/config/export", a.AdminExportConfig)
		cfgOps.GET("/config/releases", a.AdminListReleases)
		cfgOps.POST("/config/releases", a.AdminCreateRelease)
		cfgOps.POST("/config/releases/:id/deploy", a.AdminDeployRelease)
		cfgOps.GET("/config/releases/:id/export", a.AdminExportRelease)
		cfgOps.GET("/config/releases/:id/snapshot", a.AdminGetReleaseSnapshot)
		cfgOps.POST("/config/releases/:id/rollback", a.AdminRollbackRelease)

		// Permission-protected: rbac.manage (except /me/permissions — open to all admins)
		rbOps := admin.Group("", middleware.RequirePermission(a.DB, "rbac", "manage"))
		rbOps.GET("/rbac/roles", a.AdminListRoles)
		rbOps.POST("/rbac/roles", a.AdminCreateRole)
		rbOps.PUT("/rbac/roles/:id", a.AdminUpdateRole)
		rbOps.GET("/rbac/roles/:id", a.AdminGetRolePermissions)
		rbOps.DELETE("/rbac/roles/:id", a.AdminDeleteRole)
		rbOps.GET("/rbac/permissions", a.AdminListPermissions)
		rbOps.POST("/rbac/roles/:id/permissions", a.AdminAssignRolePermissions)
		rbOps.GET("/rbac/roles/:id/permissions", a.AdminGetRolePermissions)
		rbOps.POST("/rbac/admins/:adminId/role", a.AdminAssignAdminRole)
		rbOps.GET("/rbac/admins/:adminId/role", a.AdminGetAdminRole)
		rbOps.GET("/rbac/admins", a.AdminListAdmins)
		rbOps.POST("/rbac/admins", a.AdminCreateAdmin)
		rbOps.GET("/rbac/audit-logs", a.AdminListAuditLogs)
		rbOps.GET("/rbac/audit-logs/:id", a.AdminGetAuditLog)
		rbOps.GET("/rbac/login-logs", a.AdminListLoginLogs)
		rbOps.POST("/rbac/approval-flows", a.AdminCreateApprovalFlow)
		rbOps.POST("/rbac/approval-flows/:id/approve", a.AdminApproveFlowStep)
		rbOps.POST("/rbac/approval-flows/:id/reject", a.AdminRejectFlowStep)
		rbOps.GET("/rbac/approval-flows", a.AdminListApprovalFlows)

		// Open to all admins: self-permissions lookup (used by frontend sidebar)
		admin.GET("/rbac/me/permissions", a.AdminGetMyPermissions)

		// Permission-protected: special.manage
		speOps := admin.Group("", middleware.RequirePermission(a.DB, "special", "manage"))
		speOps.GET("/specials", a.AdminListSpecialPages)
		speOps.POST("/specials", a.AdminCreateSpecialPage)
		speOps.PUT("/specials/:id", a.AdminUpdateSpecialPage)
		speOps.DELETE("/specials/:id", a.AdminDeleteSpecialPage)
		speOps.GET("/campaigns", a.AdminListCampaigns)
		speOps.POST("/campaigns", a.AdminCreateCampaign)
		speOps.PUT("/campaigns/:id", a.AdminUpdateCampaign)
		speOps.DELETE("/campaigns/:id", a.AdminDeleteCampaign)
		// Live: manage permission
		liveOps := admin.Group("", middleware.RequirePermission(a.DB, "live", "manage"))
		liveOps.GET("/live/rooms", a.AdminListLiveRooms)
		liveOps.GET("/live/room/:id", a.AdminGetLiveRoomDetail)
		liveOps.POST("/live/room/:id/ban", a.AdminBanLiveRoom)
		liveOps.POST("/live/room/:id/unban", a.AdminUnbanLiveRoom)
		liveOps.POST("/live/room/:id/warn", a.AdminWarnLiveRoom)
		liveOps.GET("/live/warn-templates", a.AdminListLiveWarnTemplates)
		liveOps.POST("/live/warn-templates", a.AdminCreateLiveWarnTemplate)
		liveOps.PUT("/live/warn-templates/:id", a.AdminUpdateLiveWarnTemplate)
		liveOps.DELETE("/live/warn-templates/:id", a.AdminDeleteLiveWarnTemplate)
		liveOps.DELETE("/live/room/:id", a.AdminDeleteLiveRoom)
	}

	authd := r.Group("/api/v1")
	authd.Use(middleware.JWTAuth(jwtm))
	{
		authd.GET("/users/me", a.GetMe)
		authd.GET("/users/me/daily-rewards", a.GetMeDailyRewards)
		authd.GET("/users/me/coin-ledger", a.ListMeCoinLedger)
		authd.GET("/users/me/view-history", a.ListMyViewHistory)
		authd.DELETE("/users/me/view-history", a.ClearMyViewHistory)
		authd.DELETE("/users/me/view-history/:videoId", a.DeleteMyViewHistoryEntry)
		authd.DELETE("/users/me/view-history/articles/:articleId", a.DeleteMyArticleViewHistoryEntry)
		authd.DELETE("/users/me/view-history/live/:liveRoomId", a.DeleteMyLiveViewHistoryEntry)
		authd.GET("/users/me/view-history/settings", a.GetMyViewHistorySettings)
		authd.PUT("/users/me/view-history/settings", a.PutMyViewHistorySettings)
		authd.POST("/videos/:id/view-history", a.PostVideoViewHistory)
		authd.POST("/users/me/daily-rewards/watch", a.PostMeDailyRewardWatch)
		authd.PUT("/users/me", a.UpdateMeUsername)
		authd.PUT("/users/me/profile", a.UpdateMeProfile)
		authd.PUT("/users/me/announcement", a.UpdateMeAnnouncement)
		authd.GET("/users/me/space-privacy", a.GetMeSpacePrivacy)
		authd.PUT("/users/me/space-privacy", a.UpdateMeSpacePrivacy)
		authd.POST("/users/:userId/follow", a.ToggleFollowUser)
		authd.POST("/users/:userId/block", a.BlockUser)
		authd.GET("/users/me/follow-groups", a.ListMyFollowGroups)
		authd.POST("/users/me/follow-groups", a.CreateFollowGroup)
		authd.PUT("/users/me/follow-groups/:groupId", a.UpdateFollowGroup)
		authd.DELETE("/users/me/follow-groups/:groupId", a.DeleteFollowGroup)
		authd.GET("/users/me/following/:followeeId/groups", a.ListFolloweeGroupIDs)
		authd.POST("/users/me/follow-groups/:groupId/members", a.AddFollowGroupMember)
		authd.DELETE("/users/me/follow-groups/:groupId/members/:followeeId", a.RemoveFollowGroupMember)
		authd.PUT("/users/me/password", a.UpdateMePassword)
		authd.POST("/users/me/deletion/request", a.RequestAccountDeletion)
		authd.POST("/users/me/deletion/revoke", a.RevokeAccountDeletion)
		authd.POST("/users/me/avatar", a.UpdateMeAvatar)
		authd.GET("/users/me/dynamics", a.ListMyDynamics)
		authd.POST("/users/me/dynamics", a.PostUserDynamic)
		authd.PUT("/users/me/dynamics/:id", a.PutMyUserDynamic)
		authd.DELETE("/users/me/dynamics/:id", a.DeleteMyDynamic)
		authd.PATCH("/users/me/dynamics/:id/playback", a.PatchUserDynamicPlayback)
		authd.POST("/user-dynamics/:id/comments", a.PostDynamicComment)
		authd.POST("/user-dynamics/:id/like", a.ToggleDynamicLike)
		authd.DELETE("/dynamic-comments/:id", a.DeleteDynamicComment)
		authd.POST("/dynamic-comments/:id/like", a.ToggleDynamicCommentLike)
		authd.POST("/dynamic-comments/:id/dislike", a.ToggleDynamicCommentDislike)
		authd.POST("/dynamic-comments/:id/approve", a.ApproveDynamicComment)
		authd.POST("/dynamic-comments/:id/ignore-curated", a.IgnoreCuratedDynamicComment)
		authd.GET("/users/me/videos", a.ListMyVideos)
		authd.POST("/articles", a.PostArticle)
		authd.GET("/users/me/articles", a.ListMyArticles)
		authd.GET("/users/me/articles/:id", a.GetMyArticle)
		authd.PUT("/users/me/articles/:id", a.PutMyArticle)
		authd.PATCH("/users/me/articles/:id/playback", a.PatchArticlePlayback)
		authd.PUT("/users/me/articles/:id/cover", a.UpdateArticleCover)
		authd.DELETE("/users/me/articles/:id", a.DeleteMyArticle)
		authd.GET("/users/me/article-favorites", a.ListMyArticleFavorites)
		authd.POST("/articles/:id/view", a.PostArticleView)
		authd.POST("/articles/:id/favorite", a.ToggleArticleFavorite)
		authd.POST("/articles/:id/coin", a.PostArticleCoin)
		authd.POST("/articles/:id/comments", a.PostArticleComment)
		authd.POST("/article-comments/:id/like", a.ToggleArticleCommentLike)
		authd.POST("/article-comments/:id/dislike", a.ToggleArticleCommentDislike)
		authd.POST("/article-comments/:id/pin", a.PinArticleComment)
		authd.POST("/article-comments/:id/approve", a.ApproveArticleComment)
		authd.POST("/article-comments/:id/ignore-curated", a.IgnoreCuratedArticleComment)
		authd.DELETE("/article-comments/:id", a.DeleteArticleComment)
		authd.GET("/users/me/creator/comments", a.ListCreatorComments)
		authd.GET("/users/me/creator/danmakus", a.ListCreatorDanmakus)
		authd.DELETE("/danmakus/:id", a.DeleteDanmaku)
		authd.POST("/danmakus/:id/like", a.ToggleDanmakuLike)
		authd.DELETE("/videos/:id", a.DeleteMyVideo)
		authd.POST("/videos", a.UploadVideo)
		authd.POST("/videos/draft", a.SaveVideoDraft)
		authd.PUT("/videos/:id/draft", a.UpdateVideoDraft)
		authd.POST("/videos/:id/draft", a.UpdateVideoDraft)
		authd.POST("/videos/:id/publish", a.PublishVideoDraft)
		authd.POST("/videos/:id/replace-media", a.ReplaceVideoMedia)
		authd.GET("/users/me/videos/:id/draft-source", a.GetMyVideoDraftSource)
		authd.PUT("/videos/:id/cover", a.UpdateVideoCover)
		authd.PUT("/videos/:id", a.UpdateMyVideo)
		authd.PATCH("/videos/:id/playback", a.PatchVideoPlayback)
		authd.POST("/videos/:id/like", a.ToggleVideoLike)
		authd.POST("/videos/:id/favorite", a.ToggleVideoFavorite)
		authd.GET("/videos/:id/favorite-picker", a.GetVideoFavoritePicker)
		authd.PUT("/videos/:id/favorite-folders", a.SetVideoFavoriteFolders)
		authd.PUT("/videos/:id/favorite-folders/move", a.MoveVideoFavoriteFolder)
		authd.POST("/videos/:id/favorite-folders/:folderId", a.AddVideoToFavoriteFolder)
		authd.DELETE("/videos/:id/favorite-folders/:folderId", a.RemoveVideoFromFavoriteFolder)
		authd.POST("/videos/:id/coin", a.PostVideoCoin)
		authd.POST("/videos/:id/watch-later", a.ToggleWatchLater)
		authd.GET("/users/me/favorites", a.ListMyFavorites)
		authd.GET("/users/me/favorite-folders", a.ListMyFavoriteFolders)
		authd.POST("/users/me/favorite-folders", a.CreateFavoriteFolder)
		authd.PUT("/users/me/favorite-folders/:folderId", a.UpdateFavoriteFolder)
		authd.DELETE("/users/me/favorite-folders/:folderId", a.DeleteFavoriteFolder)
		authd.DELETE("/users/me/favorite-folders/:folderId/invalid-favorites", a.ClearInvalidFavoritesInFolder)
		authd.POST("/users/me/favorite-folders/:folderId/batch-remove", a.BatchRemoveVideosFromFavoriteFolder)
		authd.GET("/users/me/search-history", a.GetMySearchHistory)
		authd.PUT("/users/me/search-history", a.PutMySearchHistory)
		authd.POST("/users/me/search-history", a.PostMySearchHistory)
		authd.GET("/users/me/watch-later", a.ListMyWatchLater)
		authd.DELETE("/users/me/watch-later", a.ClearMyWatchLater)
		authd.DELETE("/users/me/watch-later/watched", a.ClearWatchedWatchLater)
		authd.POST("/users/me/watch-later/:id/watched", a.MarkWatchLaterWatched)
		authd.POST("/videos/:id/danmaku", a.PostDanmaku)
		authd.POST("/videos/:id/comments", a.PostComment)
		authd.DELETE("/comments/:id", a.DeleteComment)
		authd.POST("/comments/:id/pin", a.PinComment)
		authd.POST("/comments/:id/approve", a.ApproveComment)
		authd.POST("/comments/:id/ignore-curated", a.IgnoreCuratedComment)
		authd.POST("/comments/:id/like", a.ToggleLike)
		authd.POST("/comments/:id/dislike", a.ToggleDislike)
		authd.GET("/notifications/unread-summary", a.UnreadSummary)
		authd.GET("/notifications", a.ListNotifications)
		authd.GET("/notifications/:id/like-likers", a.ListNotificationLikeLikers)
		authd.PATCH("/notifications/read-by-category", a.MarkNotificationCategoryRead)
		authd.PATCH("/notifications/read-batch", a.MarkNotificationsReadBatch)
		authd.PATCH("/notifications/:id/read", a.MarkNotificationRead)
		authd.POST("/notifications/:id/mute-likes", a.MuteLikeNotification)
		authd.POST("/notifications/:id/comment-like", a.ToggleNotificationCommentLike)
		authd.POST("/notifications/:id/comment-reply", a.PostNotificationCommentReply)
		authd.DELETE("/notifications/:id", a.DeleteNotification)
		authd.GET("/dm/conversations", a.ListDmConversations)
		authd.POST("/dm/conversations", a.CreateDmConversation)
		authd.DELETE("/dm/conversations/:id", a.DeleteDmConversation)
		authd.POST("/dm/conversations/:id/reset", a.ResetDmAgentConversation)
		authd.PATCH("/dm/conversations/:id/settings", a.PatchDmConversationSettings)
		authd.GET("/dm/conversations/:id/messages", a.ListDmMessages)
		authd.POST("/dm/conversations/:id/messages", a.PostDmMessage)
		authd.POST("/reports", a.PostReport)
		// Module 3: Subtitle upload/delete (auth)
		authd.POST("/videos/:id/subtitles", a.UploadSubtitle)
		authd.DELETE("/videos/:id/subtitles/:subtitleId", a.DeleteSubtitle)
		// Module 3: ASR auto-transcription
		authd.POST("/videos/:id/subtitles/asr", a.RequestSubtitleASR)
		// Module 4: Comment enhancement (auth)
		authd.POST("/videos/:id/comments-with-image", a.PostCommentWithImage)
		authd.POST("/comments/:id/images", a.UploadCommentImage)
		authd.DELETE("/comments/:id/images/:imageId", a.DeleteCommentImage)
		authd.GET("/comments/:id/images", a.ListCommentImages)
		authd.GET("/videos/:id/comments/config", a.GetCommentSortOptions)
		authd.POST("/comments/:id/report", a.ReportComment)
		// Module 5: Creator center (auth)
		authd.POST("/videos/:id/schedule", a.SchedulePublish)
		authd.DELETE("/videos/:id/schedule", a.CancelSchedule)
		authd.GET("/users/me/creator/stats", a.GetCreatorStats)
		authd.GET("/users/me/creator/video-stats", a.GetCreatorVideoStats)
		// Creator chapter management (auth, ownership check)
		authd.POST("/videos/:id/chapters", a.CreatorCreateChapter)
		authd.DELETE("/videos/:id/chapters/:chapterId", a.CreatorDeleteChapter)
		// Module 7: Subscription feed (auth)
		authd.GET("/feed/subscription", a.GetSubscriptionFeed)
		// Module 13: Tickets (auth)
		authd.POST("/tickets", a.PostTicket)
		authd.GET("/users/me/tickets", a.ListMyTickets)
		authd.GET("/users/me/tickets/:id", a.GetMyTicket)
		authd.POST("/users/me/tickets/:id/messages", a.AddTicketMessageByUser)
		authd.POST("/users/me/tickets/:id/appeal", a.AppealTicket)
		authd.POST("/tickets/:id/satisfaction", a.PostTicketSatisfaction)
		// Module 15: Copyright (auth)
		authd.POST("/copyright/complaints", a.PostCopyrightComplaint)
		authd.GET("/users/me/copyright/complaints", a.ListMyCopyrightComplaints)
		// Module 17: Customer Service (auth)
		authd.POST("/cs/conversations", a.PostCSConversation)
		authd.GET("/users/me/cs/conversations", a.ListMyCSConversations)
		authd.GET("/users/me/cs/conversations/:id", a.GetMyCSConversation)
		authd.POST("/users/me/cs/conversations/:id/messages", a.SendCSMessageByUser)
		// Live: auth
		authd.POST("/live/room/create", a.CreateLiveRoom)
		authd.PUT("/live/room/:id", a.UpdateLiveRoom)
		authd.POST("/live/room/:id/regenerate-key", a.RegenerateStreamKey)
		authd.POST("/live/room/:id/start", a.StartLiveRoom)
		authd.POST("/live/room/:id/end", a.EndLiveRoom)
		authd.POST("/live/room/:id/cover", a.UploadLiveCover)
	}

	r.GET("/api/v1/ws/danmaku", a.ServeDanmaku)
	r.GET("/api/v1/ws/chat", a.ServeChat)
	r.GET("/api/v1/ws/live", a.ServeLiveChat)

	// SRS/node-media-server live streaming callbacks (open)
	r.POST("/api/v1/live/callback/on_publish", a.SRSOnPublish)
	r.POST("/api/v1/live/callback/on_done", a.SRSOnDone)

	// Serve HLS live streaming files (node-media-server outputs to data/live/)
	r.Static("/live-hls", "./data/live")

	// Serve local uploads (used when OSS is not configured — local storage fallback)
	r.Static("/uploads", "./data/uploads")
}

func corsMiddleware(c *gin.Context) {
	h := c.Writer.Header()
	h.Set("Access-Control-Allow-Origin", "*")
	h.Set("Access-Control-Allow-Methods", "GET, POST, PUT, PATCH, DELETE, OPTIONS")
	h.Set("Access-Control-Allow-Headers", "Authorization, Content-Type")
	if c.Request.Method == http.MethodOptions {
		c.AbortWithStatus(http.StatusNoContent)
		return
	}
	c.Next()
}
